WHENEVER SQLERROR EXIT SQL.SQLCODE
SET DEFINE OFF
ALTER SESSION SET CONTAINER = FREEPDB1;

CREATE USER IAM NO AUTHENTICATION DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER CATALOG NO AUTHENTICATION DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER COMMERCE NO AUTHENTICATION DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
CREATE USER FINANCE NO AUTHENTICATION DEFAULT TABLESPACE USERS QUOTA UNLIMITED ON USERS;
GRANT CREATE SESSION, CREATE TABLE, CREATE VIEW, CREATE SEQUENCE TO IAM, CATALOG, COMMERCE, FINANCE;

ALTER SESSION SET CURRENT_SCHEMA = IAM;
CREATE TABLE organizations (organization_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_organization_id NUMBER, org_code VARCHAR2(30) NOT NULL CONSTRAINT iam_org_code_uq UNIQUE, legal_name VARCHAR2(200) NOT NULL, status VARCHAR2(12) DEFAULT 'ACTIVE' NOT NULL CHECK (status IN ('ACTIVE','SUSPENDED','CLOSED')), created_at TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL, CONSTRAINT iam_org_parent_fk FOREIGN KEY (parent_organization_id) REFERENCES organizations(organization_id));
CREATE TABLE org_units (unit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, parent_unit_id NUMBER, unit_code VARCHAR2(30) NOT NULL, unit_name VARCHAR2(120) NOT NULL, CONSTRAINT iam_unit_uq UNIQUE (organization_id,unit_code), CONSTRAINT iam_unit_parent_fk FOREIGN KEY (parent_unit_id) REFERENCES org_units(unit_id));
CREATE TABLE addresses (address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, address_type VARCHAR2(12) CHECK (address_type IN ('OFFICE','BILLING','SHIPPING')), line1 VARCHAR2(200) NOT NULL, line2 VARCHAR2(200), city VARCHAR2(100) NOT NULL, region VARCHAR2(100), postal_code VARCHAR2(20), country_code CHAR(2) NOT NULL);
CREATE TABLE principals (principal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, username VARCHAR2(100) NOT NULL, email VARCHAR2(254) NOT NULL, principal_type VARCHAR2(12) DEFAULT 'USER' CHECK (principal_type IN ('USER','SERVICE')), enabled NUMBER(1) DEFAULT 1 CHECK (enabled IN (0,1)), created_at TIMESTAMP DEFAULT SYSTIMESTAMP, CONSTRAINT iam_principal_user_uq UNIQUE (organization_id,username), CONSTRAINT iam_principal_email_uq UNIQUE (organization_id,email));
CREATE TABLE user_profiles (principal_id NUMBER PRIMARY KEY REFERENCES principals ON DELETE CASCADE, display_name VARCHAR2(160), locale_code VARCHAR2(10), time_zone VARCHAR2(50), profile_json CLOB CHECK (profile_json IS JSON));
CREATE TABLE roles (role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, role_name VARCHAR2(80) NOT NULL, description VARCHAR2(500), CONSTRAINT iam_role_uq UNIQUE (organization_id,role_name));
CREATE TABLE permissions (permission_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, permission_key VARCHAR2(120) NOT NULL UNIQUE, resource_type VARCHAR2(60) NOT NULL, action_name VARCHAR2(40) NOT NULL);
CREATE TABLE role_permissions (role_id NUMBER NOT NULL REFERENCES roles ON DELETE CASCADE, permission_id NUMBER NOT NULL REFERENCES permissions ON DELETE CASCADE, granted_at TIMESTAMP DEFAULT SYSTIMESTAMP, PRIMARY KEY(role_id,permission_id));
CREATE TABLE principal_roles (principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, role_id NUMBER NOT NULL REFERENCES roles ON DELETE CASCADE, valid_from TIMESTAMP DEFAULT SYSTIMESTAMP, valid_until TIMESTAMP, PRIMARY KEY(principal_id,role_id), CHECK (valid_until IS NULL OR valid_until > valid_from));
CREATE TABLE teams (team_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, parent_team_id NUMBER REFERENCES teams, team_name VARCHAR2(100) NOT NULL, CONSTRAINT iam_team_uq UNIQUE(organization_id,team_name));
CREATE TABLE team_members (team_id NUMBER NOT NULL REFERENCES teams ON DELETE CASCADE, principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, member_role VARCHAR2(20) DEFAULT 'MEMBER', joined_at DATE DEFAULT SYSDATE, PRIMARY KEY(team_id,principal_id));
CREATE TABLE api_clients (client_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, owner_principal_id NUMBER REFERENCES principals, client_key VARCHAR2(64) NOT NULL UNIQUE, client_name VARCHAR2(120) NOT NULL, revoked_at TIMESTAMP);
CREATE TABLE api_scopes (scope_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, scope_name VARCHAR2(100) NOT NULL UNIQUE, description VARCHAR2(500));
CREATE TABLE client_scopes (client_id NUMBER NOT NULL REFERENCES api_clients ON DELETE CASCADE, scope_id NUMBER NOT NULL REFERENCES api_scopes, PRIMARY KEY(client_id,scope_id));
CREATE TABLE sessions (session_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, client_id NUMBER REFERENCES api_clients, issued_at TIMESTAMP DEFAULT SYSTIMESTAMP, expires_at TIMESTAMP NOT NULL, revoked_at TIMESTAMP, CHECK(expires_at > issued_at));
CREATE TABLE auth_factors (factor_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, factor_type VARCHAR2(20) CHECK(factor_type IN ('TOTP','WEBAUTHN','SMS','RECOVERY')), secret_hash RAW(64), verified_at TIMESTAMP);
CREATE TABLE password_history (history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, password_hash RAW(64) NOT NULL, changed_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE login_attempts (attempt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, principal_id NUMBER REFERENCES principals ON DELETE SET NULL, attempted_name VARCHAR2(100), source_ip VARCHAR2(45), succeeded NUMBER(1) CHECK(succeeded IN(0,1)), attempted_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE access_policies (policy_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL REFERENCES organizations, policy_name VARCHAR2(100) NOT NULL, effect VARCHAR2(8) CHECK(effect IN('ALLOW','DENY')), policy_document CLOB CHECK(policy_document IS JSON), CONSTRAINT iam_policy_uq UNIQUE(organization_id,policy_name));
CREATE TABLE policy_bindings (binding_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, policy_id NUMBER NOT NULL REFERENCES access_policies ON DELETE CASCADE, role_id NUMBER REFERENCES roles, team_id NUMBER REFERENCES teams, CHECK(role_id IS NOT NULL OR team_id IS NOT NULL));
CREATE TABLE service_accounts (service_account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, principal_id NUMBER NOT NULL UNIQUE REFERENCES principals ON DELETE CASCADE, owning_unit_id NUMBER REFERENCES org_units, purpose VARCHAR2(500));
CREATE TABLE service_credentials (credential_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, service_account_id NUMBER NOT NULL REFERENCES service_accounts ON DELETE CASCADE, public_key CLOB, valid_from TIMESTAMP DEFAULT SYSTIMESTAMP, valid_until TIMESTAMP, CHECK(valid_until IS NULL OR valid_until > valid_from));
CREATE TABLE audit_events (event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER REFERENCES organizations, principal_id NUMBER REFERENCES principals, event_type VARCHAR2(80) NOT NULL, object_type VARCHAR2(80), object_key VARCHAR2(200), event_at TIMESTAMP DEFAULT SYSTIMESTAMP, payload CLOB CHECK(payload IS JSON));
CREATE TABLE notification_preferences (principal_id NUMBER NOT NULL REFERENCES principals ON DELETE CASCADE, channel VARCHAR2(12) CHECK(channel IN('EMAIL','SMS','PUSH')), enabled NUMBER(1) DEFAULT 1 CHECK(enabled IN(0,1)), quiet_from VARCHAR2(5), quiet_to VARCHAR2(5), PRIMARY KEY(principal_id,channel));
CREATE INDEX iam_audit_org_time_ix ON audit_events(organization_id,event_at);
CREATE INDEX iam_login_name_time_ix ON login_attempts(attempted_name,attempted_at);

ALTER SESSION SET CURRENT_SCHEMA = CATALOG;
CREATE TABLE categories (category_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, parent_category_id NUMBER REFERENCES categories, category_code VARCHAR2(40) NOT NULL UNIQUE, category_name VARCHAR2(120) NOT NULL, path_key VARCHAR2(500));
CREATE TABLE brands (brand_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, brand_code VARCHAR2(30) NOT NULL CONSTRAINT cat_brand_code_uq UNIQUE, brand_name VARCHAR2(120) NOT NULL, website_url VARCHAR2(500));
CREATE TABLE suppliers (supplier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, supplier_code VARCHAR2(30) NOT NULL UNIQUE, supplier_name VARCHAR2(200) NOT NULL, status VARCHAR2(12) DEFAULT 'ACTIVE');
CREATE TABLE warehouses (warehouse_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, warehouse_code VARCHAR2(30) NOT NULL UNIQUE, warehouse_name VARCHAR2(120), address_id NUMBER, active NUMBER(1) DEFAULT 1 CHECK(active IN(0,1)));
CREATE TABLE units_of_measure (uom_code VARCHAR2(12) PRIMARY KEY, uom_name VARCHAR2(60) NOT NULL, dimension_name VARCHAR2(30), conversion_factor NUMBER(20,8) DEFAULT 1 CHECK(conversion_factor>0));
CREATE TABLE products (product_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, brand_id NUMBER REFERENCES brands, sku VARCHAR2(64) NOT NULL, product_name VARCHAR2(200) NOT NULL, description CLOB, lifecycle_status VARCHAR2(16) DEFAULT 'DRAFT' CHECK(lifecycle_status IN('DRAFT','ACTIVE','RETIRED')), created_at TIMESTAMP DEFAULT SYSTIMESTAMP, CONSTRAINT cat_product_uq UNIQUE(organization_id,sku));
CREATE TABLE product_variants (variant_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id NUMBER NOT NULL REFERENCES products ON DELETE CASCADE, variant_sku VARCHAR2(64) NOT NULL CONSTRAINT cat_variant_sku_uq UNIQUE, barcode VARCHAR2(40) CONSTRAINT cat_variant_barcode_uq UNIQUE, weight_kg NUMBER(12,4) CHECK(weight_kg>=0));
CREATE TABLE product_categories (product_id NUMBER NOT NULL REFERENCES products ON DELETE CASCADE, category_id NUMBER NOT NULL REFERENCES categories, is_primary NUMBER(1) DEFAULT 0 CHECK(is_primary IN(0,1)), PRIMARY KEY(product_id,category_id));
CREATE TABLE attributes (attribute_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, attribute_code VARCHAR2(40) NOT NULL UNIQUE, attribute_name VARCHAR2(100), data_type VARCHAR2(12) CHECK(data_type IN('TEXT','NUMBER','DATE','BOOLEAN')));
CREATE TABLE attribute_values (value_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, attribute_id NUMBER NOT NULL REFERENCES attributes ON DELETE CASCADE, display_value VARCHAR2(200) NOT NULL, sort_order NUMBER DEFAULT 0, CONSTRAINT cat_attr_value_uq UNIQUE(attribute_id,display_value));
CREATE TABLE variant_attribute_values (variant_id NUMBER NOT NULL REFERENCES product_variants ON DELETE CASCADE, value_id NUMBER NOT NULL REFERENCES attribute_values, PRIMARY KEY(variant_id,value_id));
CREATE TABLE price_lists (price_list_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, list_code VARCHAR2(30) NOT NULL, currency_code CHAR(3) NOT NULL, valid_from DATE, valid_to DATE, CONSTRAINT cat_price_list_uq UNIQUE(organization_id,list_code), CHECK(valid_to IS NULL OR valid_to>=valid_from));
CREATE TABLE product_prices (price_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, price_list_id NUMBER NOT NULL REFERENCES price_lists ON DELETE CASCADE, variant_id NUMBER NOT NULL REFERENCES product_variants, unit_price NUMBER(18,4) NOT NULL CHECK(unit_price>=0), min_quantity NUMBER DEFAULT 1 CHECK(min_quantity>0), CONSTRAINT cat_price_uq UNIQUE(price_list_id,variant_id,min_quantity));
CREATE TABLE inventory_items (item_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, variant_id NUMBER NOT NULL UNIQUE REFERENCES product_variants, uom_code VARCHAR2(12) NOT NULL REFERENCES units_of_measure, lot_controlled NUMBER(1) DEFAULT 0, serial_controlled NUMBER(1) DEFAULT 0);
CREATE TABLE stock_levels (warehouse_id NUMBER NOT NULL REFERENCES warehouses, item_id NUMBER NOT NULL REFERENCES inventory_items, on_hand NUMBER(18,4) DEFAULT 0 NOT NULL, reserved NUMBER(18,4) DEFAULT 0 NOT NULL, available AS (on_hand-reserved), PRIMARY KEY(warehouse_id,item_id), CHECK(reserved>=0));
CREATE TABLE stock_movements (movement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, warehouse_id NUMBER NOT NULL REFERENCES warehouses, item_id NUMBER NOT NULL REFERENCES inventory_items, movement_type VARCHAR2(16) CHECK(movement_type IN('RECEIPT','ISSUE','TRANSFER','ADJUSTMENT')), quantity NUMBER(18,4) NOT NULL CHECK(quantity<>0), occurred_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE purchase_orders (purchase_order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, supplier_id NUMBER NOT NULL REFERENCES suppliers, warehouse_id NUMBER NOT NULL REFERENCES warehouses, po_number VARCHAR2(40) NOT NULL UNIQUE, status VARCHAR2(16) DEFAULT 'DRAFT', ordered_at DATE);
CREATE TABLE purchase_order_lines (purchase_order_id NUMBER NOT NULL REFERENCES purchase_orders ON DELETE CASCADE, line_no NUMBER NOT NULL, item_id NUMBER NOT NULL REFERENCES inventory_items, ordered_qty NUMBER(18,4) CHECK(ordered_qty>0), unit_cost NUMBER(18,4) CHECK(unit_cost>=0), PRIMARY KEY(purchase_order_id,line_no));
CREATE TABLE receipts (receipt_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, purchase_order_id NUMBER NOT NULL REFERENCES purchase_orders, receipt_number VARCHAR2(40) NOT NULL UNIQUE, received_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE receipt_lines (receipt_id NUMBER NOT NULL REFERENCES receipts ON DELETE CASCADE, line_no NUMBER NOT NULL, po_id NUMBER NOT NULL, po_line_no NUMBER NOT NULL, received_qty NUMBER(18,4) CHECK(received_qty>0), PRIMARY KEY(receipt_id,line_no), CONSTRAINT cat_receipt_po_line_fk FOREIGN KEY(po_id,po_line_no) REFERENCES purchase_order_lines(purchase_order_id,line_no));
CREATE TABLE serial_numbers (serial_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_id NUMBER NOT NULL REFERENCES inventory_items, serial_number VARCHAR2(100) NOT NULL, warehouse_id NUMBER REFERENCES warehouses, status VARCHAR2(16), CONSTRAINT cat_serial_uq UNIQUE(item_id,serial_number));
CREATE TABLE inventory_lots (lot_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, item_id NUMBER NOT NULL REFERENCES inventory_items, lot_number VARCHAR2(80) NOT NULL, manufactured_on DATE, expires_on DATE, CONSTRAINT cat_lot_uq UNIQUE(item_id,lot_number), CHECK(expires_on IS NULL OR manufactured_on IS NULL OR expires_on>manufactured_on));
CREATE TABLE reorder_rules (warehouse_id NUMBER NOT NULL REFERENCES warehouses, item_id NUMBER NOT NULL REFERENCES inventory_items, reorder_point NUMBER(18,4) DEFAULT 0, reorder_quantity NUMBER(18,4) CHECK(reorder_quantity>0), preferred_supplier_id NUMBER REFERENCES suppliers, PRIMARY KEY(warehouse_id,item_id));
CREATE TABLE catalog_audit (audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, entity_type VARCHAR2(40), entity_id NUMBER, operation VARCHAR2(12), changed_by NUMBER, changed_at TIMESTAMP DEFAULT SYSTIMESTAMP, before_state CLOB CHECK(before_state IS JSON), after_state CLOB CHECK(after_state IS JSON));
CREATE INDEX cat_product_name_ix ON products(UPPER(product_name));
CREATE INDEX cat_stock_move_time_ix ON stock_movements(item_id,occurred_at);

ALTER SESSION SET CURRENT_SCHEMA = COMMERCE;
CREATE TABLE customers (customer_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, principal_id NUMBER, customer_number VARCHAR2(40) NOT NULL UNIQUE, customer_type VARCHAR2(12) CHECK(customer_type IN('PERSON','BUSINESS')), display_name VARCHAR2(200) NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE customer_addresses (customer_address_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER NOT NULL REFERENCES customers ON DELETE CASCADE, label VARCHAR2(60), line1 VARCHAR2(200) NOT NULL, city VARCHAR2(100), postal_code VARCHAR2(20), country_code CHAR(2), is_default NUMBER(1) DEFAULT 0);
CREATE TABLE carts (cart_id RAW(16) DEFAULT SYS_GUID() PRIMARY KEY, customer_id NUMBER REFERENCES customers, currency_code CHAR(3) NOT NULL, status VARCHAR2(12) DEFAULT 'OPEN', created_at TIMESTAMP DEFAULT SYSTIMESTAMP, expires_at TIMESTAMP);
CREATE TABLE cart_items (cart_id RAW(16) NOT NULL REFERENCES carts ON DELETE CASCADE, line_no NUMBER NOT NULL, variant_id NUMBER NOT NULL, quantity NUMBER(12,3) CHECK(quantity>0), unit_price NUMBER(18,4) CHECK(unit_price>=0), PRIMARY KEY(cart_id,line_no));
CREATE TABLE sales_orders (order_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, customer_id NUMBER REFERENCES customers, order_number VARCHAR2(40) NOT NULL CONSTRAINT com_order_number_uq UNIQUE, currency_code CHAR(3) NOT NULL, status VARCHAR2(16) DEFAULT 'PENDING', ordered_at TIMESTAMP DEFAULT SYSTIMESTAMP, subtotal NUMBER(18,4) DEFAULT 0, tax_total NUMBER(18,4) DEFAULT 0, grand_total AS (subtotal+tax_total));
CREATE TABLE order_lines (order_id NUMBER NOT NULL REFERENCES sales_orders ON DELETE CASCADE, line_no NUMBER NOT NULL, variant_id NUMBER NOT NULL, sku_snapshot VARCHAR2(64), description VARCHAR2(200), quantity NUMBER(12,3) CHECK(quantity>0), unit_price NUMBER(18,4) CHECK(unit_price>=0), line_total AS (quantity*unit_price), PRIMARY KEY(order_id,line_no));
CREATE TABLE order_addresses (order_id NUMBER NOT NULL REFERENCES sales_orders ON DELETE CASCADE, address_kind VARCHAR2(8) CHECK(address_kind IN('BILLING','SHIPPING')), line1 VARCHAR2(200), city VARCHAR2(100), postal_code VARCHAR2(20), country_code CHAR(2), PRIMARY KEY(order_id,address_kind));
CREATE TABLE order_status_history (history_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id NUMBER NOT NULL REFERENCES sales_orders ON DELETE CASCADE, old_status VARCHAR2(16), new_status VARCHAR2(16) NOT NULL, changed_by NUMBER, changed_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE carriers (carrier_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, carrier_code VARCHAR2(30) NOT NULL UNIQUE, carrier_name VARCHAR2(120), tracking_url_template VARCHAR2(500));
CREATE TABLE shipments (shipment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id NUMBER NOT NULL REFERENCES sales_orders, carrier_id NUMBER REFERENCES carriers, warehouse_id NUMBER NOT NULL, tracking_number VARCHAR2(100), status VARCHAR2(16), shipped_at TIMESTAMP, delivered_at TIMESTAMP, CHECK(delivered_at IS NULL OR shipped_at IS NULL OR delivered_at>=shipped_at));
CREATE TABLE shipment_items (shipment_id NUMBER NOT NULL REFERENCES shipments ON DELETE CASCADE, order_id NUMBER NOT NULL, order_line_no NUMBER NOT NULL, shipped_quantity NUMBER(12,3) CHECK(shipped_quantity>0), PRIMARY KEY(shipment_id,order_id,order_line_no), CONSTRAINT com_ship_line_fk FOREIGN KEY(order_id,order_line_no) REFERENCES order_lines(order_id,line_no));
CREATE TABLE tracking_events (tracking_event_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id NUMBER NOT NULL REFERENCES shipments ON DELETE CASCADE, event_code VARCHAR2(40), event_location VARCHAR2(200), event_at TIMESTAMP NOT NULL, details VARCHAR2(1000));
CREATE TABLE promotions (promotion_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, promotion_code VARCHAR2(40) NOT NULL UNIQUE, promotion_name VARCHAR2(120), starts_at TIMESTAMP, ends_at TIMESTAMP, active NUMBER(1) DEFAULT 1, CHECK(ends_at IS NULL OR ends_at>starts_at));
CREATE TABLE promotion_rules (rule_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, promotion_id NUMBER NOT NULL REFERENCES promotions ON DELETE CASCADE, rule_type VARCHAR2(30), rule_document CLOB CHECK(rule_document IS JSON), priority NUMBER DEFAULT 100);
CREATE TABLE coupons (coupon_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, promotion_id NUMBER NOT NULL REFERENCES promotions, coupon_code VARCHAR2(60) NOT NULL UNIQUE, max_uses NUMBER, used_count NUMBER DEFAULT 0, CHECK(max_uses IS NULL OR used_count<=max_uses));
CREATE TABLE coupon_redemptions (coupon_id NUMBER NOT NULL REFERENCES coupons, order_id NUMBER NOT NULL REFERENCES sales_orders, customer_id NUMBER REFERENCES customers, redeemed_at TIMESTAMP DEFAULT SYSTIMESTAMP, discount_amount NUMBER(18,4) CHECK(discount_amount>=0), PRIMARY KEY(coupon_id,order_id));
CREATE TABLE payment_intents (payment_intent_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id NUMBER NOT NULL REFERENCES sales_orders, external_reference VARCHAR2(100), amount NUMBER(18,4) CHECK(amount>0), currency_code CHAR(3), status VARCHAR2(16), created_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE returns (return_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id NUMBER NOT NULL REFERENCES sales_orders, return_number VARCHAR2(40) NOT NULL UNIQUE, reason_code VARCHAR2(30), status VARCHAR2(16), requested_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE return_lines (return_id NUMBER NOT NULL REFERENCES returns ON DELETE CASCADE, line_no NUMBER NOT NULL, order_id NUMBER NOT NULL, order_line_no NUMBER NOT NULL, quantity NUMBER(12,3) CHECK(quantity>0), disposition VARCHAR2(20), PRIMARY KEY(return_id,line_no), CONSTRAINT com_return_line_fk FOREIGN KEY(order_id,order_line_no) REFERENCES order_lines(order_id,line_no));
CREATE TABLE wishlists (wishlist_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER NOT NULL REFERENCES customers ON DELETE CASCADE, wishlist_name VARCHAR2(100), visibility VARCHAR2(10) DEFAULT 'PRIVATE', created_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE wishlist_items (wishlist_id NUMBER NOT NULL REFERENCES wishlists ON DELETE CASCADE, variant_id NUMBER NOT NULL, added_at TIMESTAMP DEFAULT SYSTIMESTAMP, note VARCHAR2(500), PRIMARY KEY(wishlist_id,variant_id));
CREATE TABLE product_reviews (review_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER NOT NULL REFERENCES customers, variant_id NUMBER NOT NULL, order_id NUMBER REFERENCES sales_orders, rating NUMBER(1) CHECK(rating BETWEEN 1 AND 5), title VARCHAR2(200), review_text CLOB, moderated_at TIMESTAMP, CONSTRAINT com_review_uq UNIQUE(customer_id,variant_id,order_id));
CREATE TABLE order_notes (note_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id NUMBER NOT NULL REFERENCES sales_orders ON DELETE CASCADE, author_principal_id NUMBER, note_type VARCHAR2(12) CHECK(note_type IN('PUBLIC','INTERNAL')), note_text CLOB NOT NULL, created_at TIMESTAMP DEFAULT SYSTIMESTAMP);
CREATE TABLE fulfillment_tasks (task_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, shipment_id NUMBER REFERENCES shipments, warehouse_id NUMBER NOT NULL, assigned_principal_id NUMBER, task_type VARCHAR2(20), task_status VARCHAR2(16), due_at TIMESTAMP);
CREATE TABLE commerce_audit (audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER, entity_type VARCHAR2(40), entity_key VARCHAR2(100), changed_by NUMBER, changed_at TIMESTAMP DEFAULT SYSTIMESTAMP, change_document CLOB CHECK(change_document IS JSON));
CREATE INDEX com_order_customer_time_ix ON sales_orders(customer_id,ordered_at);
CREATE INDEX com_tracking_ship_time_ix ON tracking_events(shipment_id,event_at);

ALTER SESSION SET CURRENT_SCHEMA = FINANCE;
CREATE TABLE currencies (currency_code CHAR(3) PRIMARY KEY, currency_name VARCHAR2(80) NOT NULL, minor_units NUMBER(1) DEFAULT 2 CHECK(minor_units BETWEEN 0 AND 4));
CREATE TABLE exchange_rates (base_currency CHAR(3) REFERENCES currencies, quote_currency CHAR(3) REFERENCES currencies, rate_date DATE, exchange_rate NUMBER(20,10) CHECK(exchange_rate>0), PRIMARY KEY(base_currency,quote_currency,rate_date));
CREATE TABLE tax_codes (tax_code_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, tax_code VARCHAR2(30) NOT NULL, description VARCHAR2(200), CONSTRAINT fin_tax_code_uq UNIQUE(organization_id,tax_code));
CREATE TABLE tax_rates (tax_rate_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, tax_code_id NUMBER NOT NULL REFERENCES tax_codes ON DELETE CASCADE, jurisdiction VARCHAR2(100), rate NUMBER(9,6) CHECK(rate BETWEEN 0 AND 1), valid_from DATE, valid_to DATE, CHECK(valid_to IS NULL OR valid_to>=valid_from));
CREATE TABLE ledger_accounts (account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, parent_account_id NUMBER REFERENCES ledger_accounts, account_code VARCHAR2(30) NOT NULL, account_name VARCHAR2(120), account_type VARCHAR2(12) CHECK(account_type IN('ASSET','LIABILITY','EQUITY','REVENUE','EXPENSE')), CONSTRAINT fin_account_uq UNIQUE(organization_id,account_code));
CREATE TABLE fiscal_periods (period_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, period_name VARCHAR2(30), starts_on DATE NOT NULL, ends_on DATE NOT NULL, status VARCHAR2(10) DEFAULT 'OPEN', CONSTRAINT fin_period_uq UNIQUE(organization_id,starts_on), CHECK(ends_on>=starts_on));
CREATE TABLE journal_entries (journal_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, period_id NUMBER NOT NULL REFERENCES fiscal_periods, journal_number VARCHAR2(40) NOT NULL UNIQUE, entry_date DATE NOT NULL, description VARCHAR2(500), status VARCHAR2(10) DEFAULT 'DRAFT', source_type VARCHAR2(30), source_id NUMBER);
CREATE TABLE journal_lines (journal_id NUMBER NOT NULL REFERENCES journal_entries ON DELETE CASCADE, line_no NUMBER NOT NULL, account_id NUMBER NOT NULL REFERENCES ledger_accounts, debit_amount NUMBER(18,4) DEFAULT 0 CHECK(debit_amount>=0), credit_amount NUMBER(18,4) DEFAULT 0 CHECK(credit_amount>=0), memo VARCHAR2(500), PRIMARY KEY(journal_id,line_no), CHECK((debit_amount=0 AND credit_amount>0) OR (credit_amount=0 AND debit_amount>0)));
CREATE TABLE invoices (invoice_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, order_id NUMBER, customer_id NUMBER, invoice_number VARCHAR2(40) NOT NULL CONSTRAINT fin_invoice_number_uq UNIQUE, currency_code CHAR(3) REFERENCES currencies, issued_on DATE, due_on DATE, status VARCHAR2(16), total_amount NUMBER(18,4) CHECK(total_amount>=0), CHECK(due_on IS NULL OR due_on>=issued_on));
CREATE TABLE invoice_lines (invoice_id NUMBER NOT NULL REFERENCES invoices ON DELETE CASCADE, line_no NUMBER NOT NULL, order_id NUMBER, order_line_no NUMBER, description VARCHAR2(300), quantity NUMBER(12,3), unit_price NUMBER(18,4), tax_code_id NUMBER REFERENCES tax_codes, PRIMARY KEY(invoice_id,line_no));
CREATE TABLE credit_notes (credit_note_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, invoice_id NUMBER NOT NULL REFERENCES invoices, credit_number VARCHAR2(40) NOT NULL UNIQUE, issued_on DATE, reason VARCHAR2(300), total_amount NUMBER(18,4) CHECK(total_amount>0));
CREATE TABLE credit_note_lines (credit_note_id NUMBER NOT NULL REFERENCES credit_notes ON DELETE CASCADE, line_no NUMBER NOT NULL, invoice_line_no NUMBER, amount NUMBER(18,4) CHECK(amount>0), description VARCHAR2(300), PRIMARY KEY(credit_note_id,line_no));
CREATE TABLE payment_methods (payment_method_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, customer_id NUMBER, method_type VARCHAR2(20), token_reference VARCHAR2(200) UNIQUE, last_four CHAR(4), expires_on DATE);
CREATE TABLE payments (payment_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, payment_intent_id NUMBER, payment_method_id NUMBER REFERENCES payment_methods, payment_reference VARCHAR2(80) NOT NULL UNIQUE, currency_code CHAR(3) REFERENCES currencies, amount NUMBER(18,4) CHECK(amount>0), status VARCHAR2(16), received_at TIMESTAMP);
CREATE TABLE payment_allocations (payment_id NUMBER NOT NULL REFERENCES payments ON DELETE CASCADE, invoice_id NUMBER NOT NULL REFERENCES invoices, allocated_amount NUMBER(18,4) CHECK(allocated_amount>0), PRIMARY KEY(payment_id,invoice_id));
CREATE TABLE bank_accounts (bank_account_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, account_name VARCHAR2(100), currency_code CHAR(3) REFERENCES currencies, account_fingerprint RAW(32) UNIQUE, active NUMBER(1) DEFAULT 1);
CREATE TABLE bank_transactions (bank_transaction_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, bank_account_id NUMBER NOT NULL REFERENCES bank_accounts, external_id VARCHAR2(100), booked_on DATE, amount NUMBER(18,4) NOT NULL, description VARCHAR2(500), reconciled NUMBER(1) DEFAULT 0, CONSTRAINT fin_bank_tx_uq UNIQUE(bank_account_id,external_id));
CREATE TABLE settlements (settlement_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, bank_account_id NUMBER NOT NULL REFERENCES bank_accounts, settlement_reference VARCHAR2(100) UNIQUE, settled_on DATE, gross_amount NUMBER(18,4), fee_amount NUMBER(18,4) DEFAULT 0);
CREATE TABLE settlement_lines (settlement_id NUMBER NOT NULL REFERENCES settlements ON DELETE CASCADE, line_no NUMBER NOT NULL, payment_id NUMBER REFERENCES payments, transaction_id NUMBER REFERENCES bank_transactions, net_amount NUMBER(18,4), PRIMARY KEY(settlement_id,line_no));
CREATE TABLE cost_centers (cost_center_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, parent_cost_center_id NUMBER REFERENCES cost_centers, cost_center_code VARCHAR2(30), cost_center_name VARCHAR2(100), CONSTRAINT fin_cost_center_uq UNIQUE(organization_id,cost_center_code));
CREATE TABLE budgets (budget_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER NOT NULL, period_id NUMBER NOT NULL REFERENCES fiscal_periods, budget_name VARCHAR2(100), status VARCHAR2(12), CONSTRAINT fin_budget_uq UNIQUE(organization_id,period_id,budget_name));
CREATE TABLE budget_lines (budget_id NUMBER NOT NULL REFERENCES budgets ON DELETE CASCADE, account_id NUMBER NOT NULL REFERENCES ledger_accounts, cost_center_id NUMBER REFERENCES cost_centers, budget_amount NUMBER(18,4) NOT NULL, PRIMARY KEY(budget_id,account_id,cost_center_id));
CREATE TABLE account_balances (account_id NUMBER NOT NULL REFERENCES ledger_accounts, period_id NUMBER NOT NULL REFERENCES fiscal_periods, opening_balance NUMBER(18,4) DEFAULT 0, debit_total NUMBER(18,4) DEFAULT 0, credit_total NUMBER(18,4) DEFAULT 0, closing_balance AS (opening_balance+debit_total-credit_total), PRIMARY KEY(account_id,period_id));
CREATE TABLE refund_transactions (refund_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, payment_id NUMBER NOT NULL REFERENCES payments, return_id NUMBER, refund_reference VARCHAR2(100) UNIQUE, amount NUMBER(18,4) CHECK(amount>0), status VARCHAR2(16), processed_at TIMESTAMP);
CREATE TABLE finance_audit (audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, organization_id NUMBER, entity_type VARCHAR2(40), entity_id NUMBER, action_name VARCHAR2(30), actor_principal_id NUMBER, action_at TIMESTAMP DEFAULT SYSTIMESTAMP, details CLOB CHECK(details IS JSON));
CREATE INDEX fin_journal_source_ix ON journal_entries(source_type,source_id);
CREATE INDEX fin_invoice_customer_ix ON invoices(customer_id,issued_on);

-- Cross-schema privileges must be direct grants for foreign-key creation.
GRANT REFERENCES ON IAM.organizations TO CATALOG, COMMERCE, FINANCE;
GRANT REFERENCES ON IAM.addresses TO CATALOG;
GRANT REFERENCES ON IAM.principals TO CATALOG, COMMERCE, FINANCE;
GRANT REFERENCES ON CATALOG.product_variants TO COMMERCE;
GRANT REFERENCES ON CATALOG.warehouses TO COMMERCE;
GRANT REFERENCES ON COMMERCE.sales_orders TO FINANCE;
GRANT REFERENCES ON COMMERCE.order_lines TO FINANCE;
GRANT REFERENCES ON COMMERCE.customers TO FINANCE;
GRANT REFERENCES ON COMMERCE.payment_intents TO FINANCE;
GRANT REFERENCES ON COMMERCE.returns TO FINANCE;

ALTER TABLE CATALOG.suppliers ADD CONSTRAINT cat_supplier_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE CATALOG.warehouses ADD CONSTRAINT cat_warehouse_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE CATALOG.warehouses ADD CONSTRAINT cat_warehouse_addr_fk FOREIGN KEY(address_id) REFERENCES IAM.addresses(address_id);
ALTER TABLE CATALOG.products ADD CONSTRAINT cat_product_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE CATALOG.price_lists ADD CONSTRAINT cat_price_list_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE CATALOG.catalog_audit ADD CONSTRAINT cat_audit_actor_fk FOREIGN KEY(changed_by) REFERENCES IAM.principals(principal_id);

ALTER TABLE COMMERCE.customers ADD CONSTRAINT com_customer_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE COMMERCE.customers ADD CONSTRAINT com_customer_principal_fk FOREIGN KEY(principal_id) REFERENCES IAM.principals(principal_id);
ALTER TABLE COMMERCE.cart_items ADD CONSTRAINT com_cart_variant_fk FOREIGN KEY(variant_id) REFERENCES CATALOG.product_variants(variant_id);
ALTER TABLE COMMERCE.sales_orders ADD CONSTRAINT com_order_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE COMMERCE.order_lines ADD CONSTRAINT com_line_variant_fk FOREIGN KEY(variant_id) REFERENCES CATALOG.product_variants(variant_id);
ALTER TABLE COMMERCE.shipments ADD CONSTRAINT com_ship_warehouse_fk FOREIGN KEY(warehouse_id) REFERENCES CATALOG.warehouses(warehouse_id);
ALTER TABLE COMMERCE.wishlist_items ADD CONSTRAINT com_wish_variant_fk FOREIGN KEY(variant_id) REFERENCES CATALOG.product_variants(variant_id);
ALTER TABLE COMMERCE.product_reviews ADD CONSTRAINT com_review_variant_fk FOREIGN KEY(variant_id) REFERENCES CATALOG.product_variants(variant_id);
ALTER TABLE COMMERCE.order_notes ADD CONSTRAINT com_note_author_fk FOREIGN KEY(author_principal_id) REFERENCES IAM.principals(principal_id);
ALTER TABLE COMMERCE.fulfillment_tasks ADD CONSTRAINT com_task_warehouse_fk FOREIGN KEY(warehouse_id) REFERENCES CATALOG.warehouses(warehouse_id);
ALTER TABLE COMMERCE.fulfillment_tasks ADD CONSTRAINT com_task_actor_fk FOREIGN KEY(assigned_principal_id) REFERENCES IAM.principals(principal_id);

ALTER TABLE FINANCE.tax_codes ADD CONSTRAINT fin_tax_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.ledger_accounts ADD CONSTRAINT fin_account_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.fiscal_periods ADD CONSTRAINT fin_period_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.journal_entries ADD CONSTRAINT fin_journal_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.invoices ADD CONSTRAINT fin_invoice_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.invoices ADD CONSTRAINT fin_invoice_order_fk FOREIGN KEY(order_id) REFERENCES COMMERCE.sales_orders(order_id);
ALTER TABLE FINANCE.invoices ADD CONSTRAINT fin_invoice_customer_fk FOREIGN KEY(customer_id) REFERENCES COMMERCE.customers(customer_id);
ALTER TABLE FINANCE.invoice_lines ADD CONSTRAINT fin_inv_line_order_fk FOREIGN KEY(order_id,order_line_no) REFERENCES COMMERCE.order_lines(order_id,line_no);
ALTER TABLE FINANCE.payment_methods ADD CONSTRAINT fin_method_customer_fk FOREIGN KEY(customer_id) REFERENCES COMMERCE.customers(customer_id);
ALTER TABLE FINANCE.payments ADD CONSTRAINT fin_payment_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.payments ADD CONSTRAINT fin_payment_intent_fk FOREIGN KEY(payment_intent_id) REFERENCES COMMERCE.payment_intents(payment_intent_id);
ALTER TABLE FINANCE.bank_accounts ADD CONSTRAINT fin_bank_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.cost_centers ADD CONSTRAINT fin_cost_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.budgets ADD CONSTRAINT fin_budget_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.refund_transactions ADD CONSTRAINT fin_refund_return_fk FOREIGN KEY(return_id) REFERENCES COMMERCE.returns(return_id);
ALTER TABLE FINANCE.finance_audit ADD CONSTRAINT fin_audit_org_fk FOREIGN KEY(organization_id) REFERENCES IAM.organizations(organization_id);
ALTER TABLE FINANCE.finance_audit ADD CONSTRAINT fin_audit_actor_fk FOREIGN KEY(actor_principal_id) REFERENCES IAM.principals(principal_id);

-- Document every seeded table and column. Keeping this data-driven ensures new
-- seed columns cannot silently be left undocumented.
DECLARE
  FUNCTION words(identifier VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN REPLACE(LOWER(identifier), '_', ' ');
  END;

  FUNCTION quoted_literal(value VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN '''' || REPLACE(value, '''', '''''') || '''';
  END;

  FUNCTION schema_purpose(owner_name VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN CASE owner_name
      WHEN 'IAM' THEN 'identity and access management'
      WHEN 'CATALOG' THEN 'product catalog and inventory management'
      WHEN 'COMMERCE' THEN 'ordering and fulfillment'
      WHEN 'FINANCE' THEN 'accounting and payment processing'
    END;
  END;

  FUNCTION table_description(owner_name VARCHAR2, table_name VARCHAR2) RETURN VARCHAR2 IS
  BEGIN
    RETURN 'Stores ' || words(table_name) || ' used for the seeded ' ||
      schema_purpose(owner_name) || ' example.';
  END;

  FUNCTION column_description(table_name VARCHAR2, column_name VARCHAR2) RETURN VARCHAR2 IS
    label VARCHAR2(200) := words(column_name);
  BEGIN
    RETURN CASE
      WHEN column_name IN ('BEFORE_STATE', 'AFTER_STATE', 'CHANGE_DOCUMENT', 'PAYLOAD',
                           'POLICY_DOCUMENT', 'PROFILE_JSON', 'RULE_DOCUMENT') OR
           (table_name = 'FINANCE_AUDIT' AND column_name = 'DETAILS')
        THEN 'JSON document containing the ' || label || '.'
      WHEN column_name LIKE '%\_ID' ESCAPE '\'
        THEN 'Identifier for the ' || REPLACE(label, ' id', '') || ' associated with this record.'
      WHEN column_name LIKE '%\_AT' ESCAPE '\'
        THEN 'Date and time when the ' || REPLACE(label, ' at', '') || ' event occurred.'
      WHEN column_name LIKE '%\_ON' ESCAPE '\'
        THEN 'Calendar date for the ' || REPLACE(label, ' on', '') || ' event.'
      WHEN column_name LIKE '%\_CODE' ESCAPE '\'
        THEN 'Business code identifying the ' || REPLACE(label, ' code', '') || '.'
      WHEN column_name LIKE '%\_NAME' ESCAPE '\'
        THEN 'Human-readable name of the ' || REPLACE(label, ' name', '') || '.'
      WHEN column_name LIKE '%\_NUMBER' ESCAPE '\'
        THEN 'Business-facing number identifying the ' || REPLACE(label, ' number', '') || '.'
      WHEN column_name LIKE '%\_REFERENCE' ESCAPE '\' OR column_name = 'EXTERNAL_ID'
        THEN 'External or business reference used to correlate this ' || words(table_name) || ' record.'
      WHEN column_name LIKE '%\_AMOUNT' ESCAPE '\' OR column_name IN
           ('SUBTOTAL', 'TAX_TOTAL', 'GRAND_TOTAL', 'UNIT_COST', 'UNIT_PRICE', 'LINE_TOTAL')
        THEN 'Monetary value represented by ' || label || ', in the record currency.'
      WHEN column_name LIKE '%QUANTITY%' OR column_name LIKE '%\_QTY' ESCAPE '\' OR
           column_name IN ('ON_HAND', 'RESERVED', 'AVAILABLE')
        THEN 'Quantity represented by ' || label || ' in the applicable unit of measure.'
      WHEN column_name IN ('ACTIVE', 'ENABLED', 'IS_DEFAULT', 'IS_PRIMARY', 'LOT_CONTROLLED',
                           'RECONCILED', 'SERIAL_CONTROLLED', 'SUCCEEDED')
        THEN 'Boolean flag indicating whether ' || label || ' is true.'
      WHEN column_name IN ('STATUS', 'TASK_STATUS', 'LIFECYCLE_STATUS')
        THEN 'Current lifecycle status of this ' || words(table_name) || ' record.'
      WHEN column_name IN ('DESCRIPTION', 'DETAILS', 'MEMO', 'NOTE', 'NOTE_TEXT', 'PURPOSE',
                           'REASON', 'REVIEW_TEXT')
        THEN 'Descriptive text providing ' || label || ' for this record.'
      WHEN column_name IN ('CURRENCY_CODE', 'COUNTRY_CODE', 'LOCALE_CODE', 'UOM_CODE')
        THEN 'Standard code specifying the ' || REPLACE(label, ' code', '') || '.'
      WHEN column_name = 'LINE_NO'
        THEN 'Sequence number uniquely locating this line within its parent record.'
      WHEN column_name IN ('VALID_FROM', 'STARTS_AT', 'STARTS_ON', 'ISSUED_AT')
        THEN 'Date or timestamp when this record becomes effective.'
      WHEN column_name IN ('VALID_TO', 'VALID_UNTIL', 'ENDS_AT', 'ENDS_ON', 'EXPIRES_AT', 'EXPIRES_ON')
        THEN 'Date or timestamp after which this record is no longer effective.'
      WHEN column_name LIKE '%\_TYPE' ESCAPE '\' OR column_name IN ('ACTION_NAME', 'CHANNEL',
           'DISPOSITION', 'EFFECT', 'OPERATION', 'VISIBILITY')
        THEN 'Classification value describing the ' || label || '.'
      WHEN column_name LIKE '%\_URL%' ESCAPE '\'
        THEN 'URL used for ' || label || '.'
      WHEN column_name LIKE '%\_HASH' ESCAPE '\' OR column_name IN
           ('ACCOUNT_FINGERPRINT', 'PUBLIC_KEY', 'SECRET_HASH', 'TOKEN_REFERENCE')
        THEN 'Non-plaintext security value used for ' || label || '.'
      ELSE 'Value of ' || label || ' for this ' || words(table_name) || ' record.'
    END;
  END;
BEGIN
  FOR table_record IN (
    SELECT owner, table_name
      FROM all_tables
     WHERE owner IN ('IAM', 'CATALOG', 'COMMERCE', 'FINANCE')
     ORDER BY owner, table_name
  ) LOOP
    EXECUTE IMMEDIATE
      'COMMENT ON TABLE ' || DBMS_ASSERT.ENQUOTE_NAME(table_record.owner) || '.' ||
      DBMS_ASSERT.ENQUOTE_NAME(table_record.table_name) || ' IS ' ||
      quoted_literal(table_description(table_record.owner, table_record.table_name));

    FOR column_record IN (
      SELECT column_name
        FROM all_tab_columns
       WHERE owner = table_record.owner
         AND table_name = table_record.table_name
       ORDER BY column_id
    ) LOOP
      EXECUTE IMMEDIATE
        'COMMENT ON COLUMN ' || DBMS_ASSERT.ENQUOTE_NAME(table_record.owner) || '.' ||
        DBMS_ASSERT.ENQUOTE_NAME(table_record.table_name) || '.' ||
        DBMS_ASSERT.ENQUOTE_NAME(column_record.column_name) || ' IS ' ||
        quoted_literal(column_description(table_record.table_name, column_record.column_name));
    END LOOP;
  END LOOP;
END;
/

BEGIN
  EXECUTE IMMEDIATE 'COMMENT ON TABLE IAM.PRINCIPALS IS ''Users'''' directory & lifecycle ' || UNISTR(CHR(92) || '2014') || ' exact text''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN IAM.PRINCIPALS.EMAIL IS ''Primary address' || CHR(10) || 'Unicode ' || UNISTR(CHR(92) || '03A9') || ' & apostrophe''''s test''';
  EXECUTE IMMEDIATE 'COMMENT ON COLUMN CATALOG.PRODUCTS.PRODUCT_NAME IS ''' || RPAD('L', 3900, 'L') || '''';
END;
/

-- Conventional views: chains, a diamond, joins, aliases, quoted names, cross-schema edges, and restrictions.
ALTER SESSION SET CURRENT_SCHEMA = CATALOG;
CREATE VIEW active_products (product_id, sku, product_name, lifecycle_status) AS
  SELECT product_id, sku, product_name, lifecycle_status FROM products WHERE lifecycle_status = 'ACTIVE'
  WITH CHECK OPTION CONSTRAINT cat_active_products_ck;
CREATE VIEW "Product Availability" (product_id, sku, product_name, available_quantity) BEQUEATH CURRENT_USER AS
  SELECT p.product_id, p.sku, p.product_name, NVL(SUM(s.available), 0)
    FROM active_products p LEFT JOIN product_variants v ON v.product_id = p.product_id
    LEFT JOIN inventory_items i ON i.variant_id = v.variant_id
    LEFT JOIN stock_levels s ON s.item_id = i.item_id
   GROUP BY p.product_id, p.sku, p.product_name
  WITH READ ONLY;

GRANT SELECT ON CATALOG.active_products TO COMMERCE;
GRANT SELECT ON CATALOG.product_variants TO COMMERCE;
ALTER SESSION SET CURRENT_SCHEMA = COMMERCE;
CREATE VIEW open_orders (order_id, customer_id, order_number, status, grand_total) BEQUEATH CURRENT_USER AS
  SELECT order_id, customer_id, order_number, status, grand_total FROM sales_orders WHERE status IN ('PENDING', 'PAID')
  WITH CHECK OPTION CONSTRAINT com_open_orders_ck;
CREATE VIEW order_product_rollup (order_id, order_number, line_count, merchandise_total) AS
  SELECT o.order_id, o.order_number, COUNT(l.line_no), NVL(SUM(l.line_total), 0)
    FROM open_orders o LEFT JOIN order_lines l ON l.order_id = o.order_id
   GROUP BY o.order_id, o.order_number
  WITH READ ONLY;

GRANT SELECT ON COMMERCE.open_orders TO FINANCE;
GRANT SELECT ON COMMERCE.order_product_rollup TO FINANCE;
ALTER SESSION SET CURRENT_SCHEMA = FINANCE;
CREATE VIEW open_order_finance (order_id, order_number, line_count, merchandise_total, invoice_id, invoice_status) AS
  SELECT o.order_id, o.order_number, r.line_count, r.merchandise_total, i.invoice_id, i.status
    FROM COMMERCE.open_orders o
    JOIN COMMERCE.order_product_rollup r ON r.order_id = o.order_id
    LEFT JOIN invoices i ON i.order_id = o.order_id
  WITH READ ONLY;

-- Boundary values are part of the ordinary reconstruction, without adding tables.
ALTER TABLE IAM.permissions ADD (
  literal_probe VARCHAR2(80 CHAR) DEFAULT 'it''s  (exact)',
  rounded_probe NUMBER(8,-2) DEFAULT 12345,
  byte_probe VARCHAR2(17 BYTE),
  char_probe VARCHAR2(17 CHAR)
);

-- Integration-test accounts for this disposable example database only.
-- Real extraction uses an existing supplied account; it never runs this seed,
-- creates these users, requires proxy authentication, or changes source grants.
-- Passwordless proxy targets: authentication uses the existing SYSTEM secret,
-- but catalog visibility and privileges belong to the restricted session user.
CREATE USER SCHEMA_READER NO AUTHENTICATION;
CREATE USER LIMITED_READER NO AUTHENTICATION;
GRANT CREATE SESSION TO SCHEMA_READER, LIMITED_READER;
ALTER USER SCHEMA_READER GRANT CONNECT THROUGH SYSTEM;
ALTER USER LIMITED_READER GRANT CONNECT THROUGH SYSTEM;
BEGIN
  FOR item IN (
    SELECT owner, object_name FROM dba_objects
    WHERE owner IN ('IAM','CATALOG','COMMERCE','FINANCE')
      AND object_type IN ('TABLE','VIEW')
  ) LOOP
    EXECUTE IMMEDIATE 'GRANT SELECT ON ' ||
      DBMS_ASSERT.ENQUOTE_NAME(item.owner, FALSE) || '.' ||
      DBMS_ASSERT.ENQUOTE_NAME(item.object_name, FALSE) || ' TO SCHEMA_READER';
  END LOOP;
END;
/
-- The child and view are visible, but their required definitions are not.
GRANT SELECT ON IAM.org_units TO LIMITED_READER;
GRANT SELECT ON COMMERCE.open_orders TO LIMITED_READER;

-- This is deliberately last. Startup and health checks use it as an atomic
-- indication that every table, grant, index, and foreign key was created.
CREATE SEQUENCE IAM.source_seed_complete START WITH 1 NOCACHE;

COMMIT;
PROMPT Source seed complete: IAM, CATALOG, COMMERCE, FINANCE (98 tables, 5 views).
EXIT SUCCESS
