-- Generated from oracle-schema-pipeline format 6. Catalog definitions and selected PL/SQL source.

WHENEVER SQLERROR EXIT SQL.SQLCODE ROLLBACK

WHENEVER OSERROR EXIT FAILURE ROLLBACK

SET DEFINE OFF

SET SQLBLANKLINES ON

SET ECHO OFF

ALTER SESSION SET DEFERRED_SEGMENT_CREATION=TRUE;

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_USERS WHERE USERNAME = 'APP';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER "APP" NO AUTHENTICATION DEFAULT TABLESPACE "USERS" QUOTA UNLIMITED ON "USERS"';
  END IF;
END;
/

DECLARE
  n NUMBER;
BEGIN
  SELECT COUNT(*) INTO n FROM ALL_USERS WHERE USERNAME = 'SHARED';
  IF n = 0 THEN
    EXECUTE IMMEDIATE 'CREATE USER "SHARED" NO AUTHENTICATION DEFAULT TABLESPACE "USERS" QUOTA UNLIMITED ON "USERS"';
  END IF;
END;
/

CREATE TABLE "APP"."CHILD" (
  "TENANT_ID" NUMBER(10,0),
  "ID" NUMBER(10,0)
) SEGMENT CREATION DEFERRED;

CREATE TABLE "SHARED"."PARENT" (
  "TENANT_ID" NUMBER(10,0),
  "ID" NUMBER(10,0)
) SEGMENT CREATION DEFERRED;

BEGIN
  EXECUTE IMMEDIATE
    'COMMENT ON TABLE "APP"."CHILD" IS ''Synthetic child table''''s comment & ' ||
    UNISTR('\03A9') ||
    '''';
END;
/

COMMENT ON COLUMN "APP"."CHILD"."TENANT_ID" IS 'Tenant identifier';

CREATE UNIQUE INDEX "APP"."PK_CHILD" ON "APP"."CHILD" ("TENANT_ID" ASC, "ID" ASC);

CREATE UNIQUE INDEX "SHARED"."PK_PARENT" ON "SHARED"."PARENT" ("TENANT_ID" ASC, "ID" ASC);

ALTER TABLE "APP"."CHILD" ADD CONSTRAINT "PK_CHILD" PRIMARY KEY ("TENANT_ID", "ID") NOT DEFERRABLE USING INDEX "APP"."PK_CHILD" ENABLE VALIDATE;

ALTER TABLE "SHARED"."PARENT" ADD CONSTRAINT "PK_PARENT" PRIMARY KEY ("TENANT_ID", "ID") NOT DEFERRABLE USING INDEX "SHARED"."PK_PARENT" ENABLE VALIDATE;

GRANT REFERENCES ON "SHARED"."PARENT" TO "APP";

ALTER TABLE "APP"."CHILD" ADD CONSTRAINT "FK_CHILD_PARENT" FOREIGN KEY ("TENANT_ID", "ID") REFERENCES "SHARED"."PARENT" ("TENANT_ID", "ID") NOT DEFERRABLE ENABLE VALIDATE;

PROMPT Schema reconstruction completed.
